# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [ubuntu-latest]    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.5' # The Go version to download (if necessary) and use.
      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint

      - name: Build
        run: go build ./cmd

      - name: Test With Coverage
        env: 
          MDK_API_TOKEN: ${{ secrets.MDK_API_TOKEN }}
          MDK_API_URL: ${{ secrets.MDK_API_URL }}
          MERCHANT_CCID: ${{ secrets.MERCHANT_CCID }}
          MERCHANT_PASSWORD: ${{ secrets.MERCHANT_PASSWORD }}
          DUMMY_REQUEST: ${{ secrets.DUMMY_REQUEST }}
          TXN_VERSION: ${{ secrets.TXN_VERSION }}
          ACCOUNT_API_URL: ${{ secrets.ACCOUNT_API_URL }}
          PAYMENT_API_URL: ${{ secrets.PAYMENT_API_URL }}
          SEARCH_API_URL: ${{ secrets.SEARCH_API_URL }}
        run: |
          go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      
      - name: Run Vet & Lint
        run: |
          go vet ./...
          golint -set_exit_status=1 ./...
